services:


  translate_api:
    build:
      context: nodejs-google-translate-api
      dockerfile: Dockerfile
    networks:
      - common-network
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
    volumes:
      - ./src:/src:rw
    env_file:
      - .env
    depends_on:
      - mongo
      - translate_api
    ports:
      - 8000:8000
    networks:
      - common-network
      - default


  mongo:
    image: mongo:4.4.8
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command:
      [ "--auth" ]
    ports:
      - 27017:27017
    networks:
      - common-network
      - default



networks:
  default:
    driver: bridge
  common-network:
    external: true
